### ISSUE TITLE
[restore-mtime] Add instructions for GitHub Actions in documentation

### ISSUE THREAD

**Issue by heldersepu** [MestreLion/git-tools#44]
Here is the data I can share....

locally it works fine the output shows:
```
36 files to be processed in work dir
Statistics:
         0.02 seconds
          762 log lines processed
           73 commits evaluated
           36 updated files
            8 updated directories
```

On github action it shows:
```
36 files to be processed in work dir
Statistics:
         0.02 seconds
           38 log lines processed
            1 commits evaluated
           36 updated files
           10 updated directories
```
As we can see there are a lot less log lines processed in the pipeline
I get a feeling this might be similar to Issue https://github.com/MestreLion/git-tools/issues/29

**Comment by heldersepu** [comment]
Yep, that was the same as TravisCI....
this fix it for me:
https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches

**Comment by MestreLion** [comment]
Thanks for the report and for sharing the fix, @heldersepu !

> Yep, that was the same as TravisCI....
> this fix it for me:
> https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches

I'm willing to improve the documentation to add this hint to the [README.md](../tree/master/README.md), just like I did regarding TravisCI, but... I've read the document, and I'm completely clueless on _where_ to set this `fetch-depth: 0`. 

I'm thinking about something along the lines of:

"Similarly, when using Github Actions, make sure to set `fetch-depth: 0` in your..."

But I have no idea how to properly word such instructions. Any suggestions?

**Comment by MestreLion** [comment]
Maybe this?

Similarly, when using Github Actions, make sure to include a `fetch-depth: 0` directive*** in your checkout action as described in its [documentation](https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches), for example:

```yaml
- uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

***: Directive? Instruction? Parameter?

Yes, clearly I've never used Github actions before, lol.

**Comment by heldersepu** [comment]
Hopefully this clarifies where the fetch-depth goes

`.github/workflows/terraform.yml`
```
name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Versions
      run: terraform version -json; npm version; aws --version

...
```
